"""Builds analysis.ipynb from a list of (markdown | code) cell definitions.

Kept as a script (rather than hand-editing notebook JSON) so the notebook's
content is easy to review and regenerate.
"""
from __future__ import annotations

from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parent.parent


def md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text.strip() + "\n")


def code(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(text.strip() + "\n")


cells = [
    md("""
# Retail Sales Analysis

A SQL-first analysis of a synthetic retail dataset (600 customers, ~3,200 completed
orders, 20 products across 5 categories, spanning Jan 2023 &ndash; Jun 2025).

The database is generated by `generate_data.py` (deterministic, seeded) and the
underlying queries live in `queries/*.sql` so each one can be read, run, and
reviewed independently of this notebook &mdash; this notebook just runs them,
visualizes the results, and writes up what they mean.

**Schema:** `customers` &rarr; `orders` &rarr; `order_items` &larr; `products` &rarr; `categories`
(see `schema.sql`).
"""),
    code("""
import sqlite3
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

sns.set_theme(style="whitegrid", palette="deep")
plt.rcParams["figure.dpi"] = 110

ROOT = Path.cwd()
DB_PATH = ROOT / "retail.db"
QUERIES = ROOT / "queries"

conn = sqlite3.connect(DB_PATH)

def run_query(filename: str) -> pd.DataFrame:
    sql = (QUERIES / filename).read_text()
    return pd.read_sql_query(sql, conn)
"""),
    md("""
## 1. Monthly revenue trend

Is revenue actually growing, and how volatile is month-over-month growth?
"""),
    code("""
revenue = run_query("01_monthly_revenue_trend.sql")
revenue["month"] = pd.to_datetime(revenue["month"])
revenue.tail(8)
"""),
    code("""
fig, ax1 = plt.subplots(figsize=(10, 4.5))
ax1.plot(revenue["month"], revenue["revenue"], marker="o", color="#214C6A")
ax1.set_ylabel("Revenue ($)")
ax1.set_title("Monthly revenue trend")
ax1.set_xlabel("")
fig.autofmt_xdate()
plt.tight_layout()
plt.show()
"""),
    md("""
**Finding:** revenue is choppy in the first few months (small customer base, low order
volume) and smooths out into a clearer upward trend from mid-2023 onward as the customer
base compounds. November/December show a visible seasonal bump in most years, consistent
with the seasonality built into order timing.
"""),
    md("""
## 2. Top customers by lifetime value

Who are the 20 highest-value customers, and how concentrated is revenue among them?
"""),
    code("""
top_customers = run_query("02_top_customers_ltv.sql")
top_customers.head(10)
"""),
    code("""
fig, ax = plt.subplots(figsize=(9, 5))
top10 = top_customers.head(10).sort_values("lifetime_value")
ax.barh(top10["customer_name"], top10["lifetime_value"], color="#B45309")
ax.set_xlabel("Lifetime value ($)")
ax.set_title("Top 10 customers by lifetime value")
plt.tight_layout()
plt.show()
"""),
    code("""
total_revenue = run_query("01_monthly_revenue_trend.sql")["revenue"].sum()
top20_revenue = top_customers["lifetime_value"].sum()
share = top20_revenue / total_revenue
print(f"Top 20 customers ({len(top_customers)}) account for {share:.1%} of total completed revenue.")
"""),
    md("""
**Finding:** the top 20 customers (out of 600) contribute a disproportionate share of
revenue &mdash; a classic long-tail pattern. This is the kind of number that would justify
a VIP retention program in a real business.
"""),
    md("""
## 3. Product performance within category

Which products lead their category, and how concentrated is category revenue among
a handful of SKUs?
"""),
    code("""
product_rank = run_query("03_product_rank_within_category.sql")
product_rank[product_rank["rank_in_category"] == 1]
"""),
    code("""
fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(
    data=product_rank,
    x="pct_of_category_revenue", y="product_name", hue="category_name",
    dodge=False, ax=ax,
)
ax.set_xlabel("% of category revenue")
ax.set_ylabel("")
ax.set_title("Each product's share of its category's revenue")
ax.legend(title="Category", bbox_to_anchor=(1.02, 1), loc="upper left")
plt.tight_layout()
plt.show()
"""),
    md("""
**Finding:** in every category, the #1 product by revenue takes a noticeably larger
share than the rest of the lineup &mdash; useful for deciding where to focus inventory
and marketing spend, and which underperforming SKUs might be worth cutting.
"""),
    md("""
## 4. Signup-month cohort retention

Of customers who signed up in a given month, what share come back and order again in
each of the following 3 months?
"""),
    code("""
cohorts = run_query("04_signup_cohort_retention.sql")
cohorts["m1_retention"] = (cohorts["month_1_active"] / cohorts["month_0_active"]).round(2)
cohorts["m2_retention"] = (cohorts["month_2_active"] / cohorts["month_0_active"]).round(2)
cohorts["m3_retention"] = (cohorts["month_3_active"] / cohorts["month_0_active"]).round(2)
cohorts[["cohort_month", "month_0_active", "m1_retention", "m2_retention", "m3_retention"]].tail(10)
"""),
    code("""
avg_retention = cohorts[["m1_retention", "m2_retention", "m3_retention"]].mean()
fig, ax = plt.subplots(figsize=(6, 4))
ax.bar(["Month 1", "Month 2", "Month 3"], avg_retention.values, color="#3D7A59")
ax.set_ylabel("Average retention rate")
ax.set_title("Average cohort retention by month since signup")
ax.set_ylim(0, max(avg_retention.values) * 1.3)
for i, v in enumerate(avg_retention.values):
    ax.text(i, v + 0.01, f"{v:.0%}", ha="center")
plt.tight_layout()
plt.show()
"""),
    md("""
**Finding:** retention drops off sharply after the signup month, which is typical for
retail &mdash; the biggest lever for revenue growth is usually converting more first-time
buyers into second-time buyers, not just acquiring new customers.
"""),
    md("""
## 5. Churn risk: customers going quiet

Customers with at least 3 completed orders whose current gap since their last order is
more than 2x their own historical average gap &mdash; a simple, explainable "at risk"
flag a retention team could act on directly.
"""),
    code("""
at_risk = run_query("05_churn_risk.sql")
at_risk.head(15)
"""),
    code("""
print(f"{len(at_risk)} repeat customers currently look at-risk by this rule.")
print("Regions most represented in the at-risk list:")
print(at_risk["region"].value_counts())
"""),
    md("""
**Finding:** this rule surfaces a concrete, actionable list &mdash; each of these
customers has an established ordering rhythm (3+ past orders) that has now gone quiet
well beyond their own normal gap, which is a stronger signal than a flat "hasn't ordered
in 90 days" rule that ignores how often that customer normally buys.
"""),
    md("""
## Summary

- Revenue trend is choppy early, then compounds — seasonality (Nov/Dec) is visible.
- Revenue is concentrated in a long tail of top customers: worth a VIP/retention play.
- Category leaders dominate their category's revenue — informs inventory/marketing focus.
- Retention falls off fast after signup month — first-to-second purchase conversion is
  the highest-leverage lever here, not just acquisition.
- A gap-ratio churn rule (vs. a flat days-since-last-order cutoff) gives a more
  personalized, explainable at-risk list.
"""),
]

nb = nbf.v4.new_notebook()
nb["cells"] = cells
nb["metadata"] = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3"},
}

out_path = ROOT / "analysis.ipynb"
nbf.write(nb, out_path)
print(f"Wrote {out_path}")
